-- JolliBeep Supabase schema
-- Run this in Supabase Dashboard > SQL Editor.

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null default '',
    email text not null unique,
    gender text default '',
    mobile text default '',
    dob date,
    username text not null unique,
    password_hash text not null,
    region text default '',
    province text default '',
    city text default '',
    barangay text default '',
    created_at timestamptz not null default now(),
    is_admin integer not null default 0
);

create table if not exists public.orders (
    order_no text primary key,
    user_id bigint references public.users(id) on delete set null,
    customer_name text not null default '',
    store_name text not null default '',
    order_type text not null default 'Pickup',
    payment_method text not null default 'Cash',
    notes text default '',
    delivery_details jsonb not null default '{}'::jsonb,
    items jsonb not null default '[]'::jsonb,
    extras jsonb not null default '[]'::jsonb,
    subtotal numeric(12,2) not null default 0,
    extras_total numeric(12,2) not null default 0,
    delivery_fee numeric(12,2) not null default 0,
    grand_total numeric(12,2) not null default 0,
    status text not null default 'Pending',
    scheduled_for text default '',
    rider_name text default '',
    receipt_date text default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create index if not exists orders_store_name_idx on public.orders (store_name);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

-- This app uses its own PHP login, so keep Row Level Security off unless
-- you later add Supabase Auth and policies.
alter table public.users disable row level security;
alter table public.orders disable row level security;
